FROM mysql:5.7.38

ENV MYSQL_ALLOW_EMPTY_PASSWORD true

ARG MYSQL_DATABASE=revistajus_production
ARG MYSQL_USER=root
ARG MYSQL_PASSWORD=1234
ARG MYSQL_ROOT_PASSWORD=12345

EXPOSE 3306

CMD ["mysqld"]
